//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC8amDragon_16092021.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbSuperstarEntities : DbContext
    {
        public DbSuperstarEntities()
            : base("name=DbSuperstarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustomControl> CustomControls { get; set; }
        public virtual DbSet<RegisterForm> RegisterForms { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
    }
}
